export default [
    {
      id: 1,
      title: "STARCANDY Cute Polar Bear Spiral Notebook Diary",
      price: 249.0,
      img: "https://m.media-amazon.com/images/I/51E2T9XNQgS._AC_UY218_.jpg",
      quantity: 1,
    },
    {
      id: 2,
      title: "STARCANDY Death Note Notebook Spiral Diary Notebook A5",
      price: 259.0,
      img: "https://m.media-amazon.com/images/I/51YSnBeD4bS._AC_UY218_.jpg",
      quantity: 1,
    },
    {
      id: 3,
      title: "STARCANDY Be The Best Version Of You Quote",
      price: 231.0,
      img: "https://m.media-amazon.com/images/I/41o9mBjLWUS._SX258_BO1,204,203,200_.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "STARCANDY Work Hard Dream Big",
      price: 349.0,
      img: "https://m.media-amazon.com/images/I/41nHRHOVifS._SX258_BO1,204,203,200_.jpg",
      quantity: 1,
    },
    {
      id: 5,
      title: "STARCANDY Cute Panda Inner Peace",
      price: 201.0,
      img: "https://m.media-amazon.com/images/I/41CJMQkNSqS._SX258_BO1,204,203,200_.jpg",
      quantity: 1,
    },
    {
      id: 6,
      title: "STARCANDY Golden King Lion Art Diary",
      price: 291.0,
      img: "https://m.media-amazon.com/images/I/51uy8tTDmGS._SX258_BO1,204,203,200_.jpg",
      quantity: 1,
    },
    {
      id: 7,
      title: "STARCANDY Sab Moh Maya Hai Monk",
      price: 289.0,
      img: "https://m.media-amazon.com/images/I/41ZH9sgRLeS._SX258_BO1,204,203,200_.jpg",
      quantity: 1,
    },
    {
      id: 8,
      title: "STARCANDY Cute Couple Love Boy & Girl Spiral",
      price: 899.0,
      img: "https://m.media-amazon.com/images/I/41sMa6UbRSS._SX258_BO1,204,203,200_.jpg",
      quantity: 1,
    },
    {
      id: 9,
      title: "STARCANDY Cute Best Friends Forever Gift Diary",
      price: 221.0,
      img: "https://m.media-amazon.com/images/I/41D2yGMtxHS._SX258_BO1,204,203,200_.jpg",
      quantity: 1,
    },
    {
      id: 10,
      title: "STARCANDY Sherlock TV Series Detective",
      price: 111.0,
      img: "https://m.media-amazon.com/images/I/51YDNZkou8S._SY450_.jpg",
      quantity: 1,
    },
    {
      id: 11,
      title: "STARCANDY Death Note Kira Notebook",
      price: 201.0,
      img: "https://m.media-amazon.com/images/I/41mGsBaz0pS._SX258_BO1,204,203,200_.jpg",
      quantity: 1,
    },
    {
      id: 12,
      title: "STARCANDY Death Note Light Yagami Notebook",
      price: 681.0,
      img: "https://m.media-amazon.com/images/I/41soy5Ld0yS._SX258_BO1,204,203,200_.jpg",
      quantity: 1,
    },
    {
      id: 13,
      title: "STARCANDY Good Things Positive Quote Printed",
      price: 201.0,
      img: "https://m.media-amazon.com/images/I/51XJhLG5BdS._SX258_BO1,204,203,200_.jpg",
      quantity: 1,
    },

    {
      id: 14,
      title: "STARCANDY Sherlock Art Holmes TV Series",
      price: 701.0,
      img: "https://m.media-amazon.com/images/I/61nikKCN6yS._SY450_.jpg",
      quantity: 1,
    }, {
      id: 15,
      title: "STARCANDY Astronaut Resting In Space Printed",
      price: 201.0,
      img: "https://m.media-amazon.com/images/I/4163S9lbpkS._SX258_BO1,204,203,200_.jpg",
      quantity: 1,
    }, {
      id: 16,
      title: "STARCANDY Hera Pheri Ye Babu Rao Ka Style Hai",
      price: 291.0,
      img: "https://m.media-amazon.com/images/I/518Kpq-y1aS._SX258_BO1,204,203,200_.jpg",
      quantity: 1,
    },
  ];
  